### ISSUE TITLE
More Manhattan plot issues

### ISSUE THREAD

**Issue by michaelofrancis** [Cloufield/gwaslab#12]
Hi, hope you're doing great. I have two requests for improvements.

1. Unfortunately I still see an issue with chromosome spacing in the package.

The current gwaslab package options allow for rank-based spacing, where centromeres (e.g. in chr1 and chr9) are no longer shown, or, for some reason way-too-wide spaces in the later chromosomes (see image)
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/51752343/232560033-7d31d816-0176-4392-a4de-92a4314c1dc8.png">

Ideally a Manhattan plot will have equal spacing between chromosomes, see the link for an example. This seems unachievable in the current package.
https://www.nature.com/articles/s41586-022-05448-9/figures/1

2. Is it possible to enable saving to svg, where the points in the manhattan plot are rasterized but the additional features (i.e. text, axes, etc.) are vector-based and editable in illustrator? In matplotlib, you can use `rasterized = True` for certain plot elements to render them as flat, while leaving other elements as vectors. 

Thanks!

**Comment by Cloufield** [comment]
Hi,
1. the plot you show looks perfect. The "way-too-wide" spaces are not errors but mostly reflect the heterochromatin (see [figure 3 in https://genome.cshlp.org/content/15/12/1759.long](https://genome.cshlp.org/content/15/12/1759/F3.expansion.html)). Centromeres alone are much shorter. I think we can either remove all spacing (rank-based) or keep all spacing (physical-position-based; default), instead of keeping spacing for some chromosomes and remove the others. If you still need this, I will prabably implement this within this week. By the way, the spacing between chromosomes are specified by `chrpad=0.03` in gwaslab. 
2. Simply you can add `scatter_kwargs={"rasterized":True}` in `plot_mqq()` to pass arguments to seaborn scatterplot which is used for Manhattan plot.

**Comment by Cloufield** [comment]
You can add `drop_chr_start=True` now in gwaslab v3.4.6.
<img width="903" alt="image" src="https://user-images.githubusercontent.com/40289485/232805421-fd6b169b-3799-4624-9e09-00d3c884a2b2.png">

**Comment by Cloufield** [comment]
Oh, I guess y axis conversion does not work properly... I haven't replicated this error yet. Would you please let me know the script you used to create the plot? Thanks.

**Comment by michaelofrancis** [comment]
Thanks, here it is:
`mysumstats.plot_mqq(mode="m",
                    cut=35,
                    cut_log=True,
                    cut_line_color="#FFFFFF", 
                    scaled=True,
                    jagged=True,
                    colors=["#31A0CC", "#126080"],
                    highlight_color="#CC4560",
                    anno_alias={"rs11590557":"SSBP3",
                                "rs79742895":"KANK4",
                                "rs1200114":"ATP1B1",
                                "rs2093985": "LAMC1",
                                "rs74882680":"THSD7A",
                               "rs150990106":"LAMB1",
                                "rs1138714":"CD151/PIDD1",
                                "rs12439253":"RORA",
                                "rs9303111":"HS3ST3B1",
                               "rs11659559":"TCF4",
                               "rs141208202":"LAMA5",
                               "rs114065856":"COL18A1"},
                    marker_size=(3,3),
                    sig_line=True,
                    sig_level=5e-8,
                    sig_line_color="red",
                    ylabels=[5,10,15,20,25,30,35,508],
                    use_rank=False,
                    sc_linewidth=1,
                    xpad=0.0,
                    highlight=h,
                    highlight_windowkb =100,
                    figargs={"figsize":(14,3.7),"dpi":800},
                    save="/Users/michaelfrancis/Documents/Fuchs_GWAS/Manhattan fig2/GWASlab/manhatta.04182023.svg",
                    saveargs={"dpi":800,"facecolor":"white"},
                    fontsize=10.8,
                    scatter_kwargs={"rasterized":True},
                    font_family="Arial")`

**Comment by michaelofrancis** [comment]
Thanks, here it is:
`mysumstats.plot_mqq(mode="m",
                    cut=35,
                    cut_log=True,
                    cut_line_color="#FFFFFF", 
                    scaled=True,
                    jagged=True,
                    colors=["#31A0CC", "#126080"],
                    highlight_color="#CC4560",
                    #anno="GENENAME",
                    anno_alias={"rs11590557":"SSBP3",
                                "rs79742895":"KANK4",
                                "rs1200114":"ATP1B1",
                                "rs2093985": "LAMC1",
                                "rs74882680":"THSD7A",
                               "rs150990106":"LAMB1",
                                "rs1138714":"CD151/PIDD1",
                                "rs12439253":"RORA",
                                "rs9303111":"HS3ST3B1",
                               "rs11659559":"TCF4",
                               "rs141208202":"LAMA5",
                               "rs114065856":"COL18A1"},
                    marker_size=(3,3),
                    sig_line=True,
                    sig_level=5e-8,
                    sig_line_color="red",
                    ylabels=[5,10,15,20,25,30,35,508],
                    use_rank=False,
                    sc_linewidth=1,
                    xpad=0.0,
                    highlight=h,
                    highlight_windowkb =100,
                    figargs={"figsize":(14,3.7),"dpi":800},
                    save="manhatta.04182023.svg",
                    saveargs={"dpi":800,"facecolor":"white"},
                    fontsize=10.8,
                    scatter_kwargs={"rasterized":True},
                    font_family="Arial")`

**Comment by michaelofrancis** [comment]
There is also one additional issue which you can see on the latest plot I posted, which is that the arrow at "TCF4" is covering up some points. I think fixing the svg rendering would allow this to be easily fixed, though. Just wanted to point it out.

**Comment by Cloufield** [comment]
> "TCF4" is covering up some points. 

Probably this is fixed in v3.4.7. Previously the auto-extraction of lead variants was using P.  This might cause problems when p is too small. Now in gwaslab v3.4.7, it will use MLOG10P if `scaled=True`. 

> even though "Arial" font is specified, I don't think the gene name labels are Arial.

Fixed, and also you can use `anno_args` to specify annotation parameters.

> the lines between the labels to the points.

Sorry that I haven`t been able to replicate this error. Can you try v3.4.7 first? If this still happens, I guess it will be helpful if you could provide more details like the log?  Thanks!

Example:
```
mysumstats.plot_mqq(
                    mode="m", 
                    cut=35, 
                    skip=3,
                    cut_log=True, 
                    scaled=True,
                    pinpoint=["11:2858546_C_T"],
                    cut_line_color="#FFFFFF",  
                    colors=["#31A0CC", "#126080"], 
                    highlight = ["11:2858546_C_T","3:185495320_G_A"],
                    highlight_color="#CC4560", 
                    anno_alias={"11:2858546_C_T":"ABCDE"}, 
                    marker_size=(3,3), 
                    sig_line=True, 
                    sig_level=5e-8, 
                    sig_level_lead = 5e-30,
                    sig_line_color="red", 
                    ylabels=[5,10,15,20,25,30,35,508], 
                    use_rank=False, 
                    sc_linewidth=1, 
                    figargs={"figsize":(14,3.7),"dpi":800}, 
                    save="manhatta.04182023.svg", 
                    saveargs={"dpi":800,"facecolor":"white"}, 
                    scatter_kwargs={"rasterized":True}, 
                    anno_args={"fontstyle":"normal"},
                    jagged=True, 
                    drop_chr_start=True,
                    xpad=0.005,
                    fontsize=10, 
                    font_family="Arial"
                   )
```

![image](https://user-images.githubusercontent.com/40289485/232960541-0bc2fc90-66d1-4f16-a0d4-2753c8fdef6e.png)

**Comment by michaelofrancis** [comment]
Hey, thank you for implementing those fixes, very nice. However, the lines are still not working correctly. I just ran your exact code and still getting issues with the lines. The png preview in VScode looks fine but did you try opening the svg output? 
<img width="857" alt="image" src="https://user-images.githubusercontent.com/51752343/233110077-049a26b5-3754-470a-95ba-fa509ff75c17.png">

**Comment by Cloufield** [comment]
It is quite complicated for pdf and svg somehow. You can try replacing `figargs={"figsize":(14,3.7),"dpi":800}` with `figargs={"figsize":(14,3.7),"dpi":72}` for now (It seems that the figure dpi affects the saved svg and pdf files). I will probably fix this and update gwaslab after more testing.

**Comment by michaelofrancis** [comment]
Yeah, this works. Thank you so much, amazing package.
